### ISSUE TITLE
[9.0] Error al descomprimir módulo

### ISSUE THREAD

**Issue by edser-pcg** [odoo-chile/l10n_cl_pos_credit_card_voucher#1]
Al descomprimir el archivo zip de este módulo el Odoo da un error interno de forma inmediata, sin ni siquiera hacer intento de instalar ni nada.

Esto solo ocurre cuando es descargado desde github, el que se encuentra en Odoo Apps no sucede.

**Comment by Danisan** [comment]
Y cual es el error que da en el log?

**Comment by edser-pcg** [comment]
@Danisan puedo pasarte el log completo pero es un poco cargado pues es de un servidor de prueba y tengo varias DB allí.

**Comment by Danisan** [comment]
Cierro el Issue porque no hay elementos para poder hacer debug. Cuando haya un elemento concreto lo reabro.
